"""add: create a table Tasks

Revision ID: 18acb5a7bd29
Revises: 39eed2a9f80a
Create Date: 2026-07-16 14:52:30.856446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18acb5a7bd29'
down_revision: Union[str, Sequence[str], None] = '39eed2a9f80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
