"""add: create a table Tasks

Revision ID: 39eed2a9f80a
Revises: 7e41b8bb9758
Create Date: 2026-07-16 14:51:43.089376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39eed2a9f80a'
down_revision: Union[str, Sequence[str], None] = '7e41b8bb9758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
