"""fix: edit type String -> Enum in table tasks for priority

Revision ID: 4210d5ec56f5
Revises: bff4494f4fdf
Create Date: 2026-07-16 15:07:01.659230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4210d5ec56f5'
down_revision: Union[str, Sequence[str], None] = 'bff4494f4fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ASAP', 'HIGH', 'MEDIUM', 'LOW', name='priority'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('ASAP', 'HIGH', 'MEDIUM', 'LOW', name='priority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
