"""fix: edit type String -> Enum in table tasks for priority

Revision ID: b9d8d94a3594
Revises: 4210d5ec56f5
Create Date: 2026-07-16 15:08:26.619602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d8d94a3594'
down_revision: Union[str, Sequence[str], None] = '4210d5ec56f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ASAP', 'HIGH', 'MEDIUM', 'LOW', name='priority', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('ASAP', 'HIGH', 'MEDIUM', 'LOW', name='priority', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
