"""fix: in table tasks: change type priority from enum to int

Revision ID: c87d0ec851d3
Revises: 5c65a2445dd9
Create Date: 2026-07-16 23:25:33.886044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87d0ec851d3'
down_revision: Union[str, Sequence[str], None] = '5c65a2445dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
