"""add telegram_chat_id to users

Revision ID: fe600e2fbf0b
Revises: c87d0ec851d3
Create Date: 2026-07-21 20:54:33.880340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe600e2fbf0b'
down_revision: Union[str, Sequence[str], None] = 'c87d0ec851d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
